### ISSUE TITLE
有关普化实验报告知识产权的疑惑

### ISSUE THREAD

**Issue by zjuerDFL** [ZJU-Mix/ourMIX#1]
![Screenshot_20240730_222844](https://github.com/user-attachments/assets/a8ed8670-e02d-4220-81e0-1fd23dc67699)

作者您好，我在您的网站上看到了未经我本人允许便在公网上发布的普化实验报告内容。
请您**尊重知识产权**，根据《中华人民共和国著作权法》第五十二条相关规定，在**24h内**将我的实验报告做彻底**下架删除处理**并向我**致歉**。我不授权您在网站上保留我的实验报告，或以任何形式在任何渠道传播相关内容。请将下架的处理结果通过邮箱发送我：zjuerdfl@zju.edu.cn

**Comment by for-mydream** [comment]
感谢，我将会删除处理，感谢提醒

**Comment by zjuerDFL** [comment]
作者您好，我在最近的commit记录中已经看到了您删除相关文件并提交，但相关处理是不可接受的。

<img width="537" alt="截屏2024-07-31 16 30 47" src="https://github.com/user-attachments/assets/98a5e219-84fe-41ed-b04e-2d3ff84dff0a">

仍有以下问题需要作者尽快处理:

1. 我**尚未收到作者给出的任何正式致歉**，请作者在**24h之内公开致歉**或**通过邮件致歉**;

2. 作者所使用的删除方式是**不彻底的**，在**之前的版本**中仍可以找到我的实验报告（如下图所示），仍然构成对我**知识产权的持续侵害**，我在此严正抗议。请作者在**24h之内**将我的文件**彻底删除**，并通过**邮件告知我**。

<img width="979" alt="截屏2024-07-31 16 32 45" src="https://github.com/user-attachments/assets/13fd057d-67f4-4999-af4b-5ac3df6a0e32">
