### ISSUE TITLE
关于贵网站 LICENSE 以及首页声明的疑问

### ISSUE THREAD

**Issue by TonyCrane** [ZJU-Mix/ourMIX#2]
您好，在贵网站首页看到了如下信息：

> 关于知识共享：本项目的许可证为[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)，任何情况下，请注明出处。
> 
> 另外，在原有协议之上，对于所有此网站原创内容，包括此网站链接（不包括借鉴图灵网站的内容），仅限本人或团队成员分享，禁止外传

在基于图灵班网站继承而来的 CC BY-NC-SA 4.0 协议之外，贵网站附加了限制，即仅限团队内部成员分享网站原创内容。不知贵团队是否有详细查阅 CC BY-NC-SA 4.0 协议的内容。

该协议第三条 b 款第 (3) 项明确：

> 3. You may not offer or impose any additional or different terms
          or conditions on, or apply any Effective Technological
          Measures to, Adapted Material that restrict exercise of the
          rights granted under the Adapter's License You apply.

即您不得提出或施加任何附加或不同的条款或条件、或在演绎作品上应用任何有效的技术措施，以限制使用者行使依您所适用的“演绎作者的许可”协议所授予的权利。

也就是说，为了遵守上游的协议，您不得提出额外的限制条件。

同时，协议第六条 a 款也声明：

> a. This Public License applies for the term of the Copyright and
     Similar Rights licensed here. However, if You fail to comply with
     this Public License, then Your rights under this Public License
     terminate automatically.

即如果您不遵守上游许可协议，则依据此公共许可协议享有的权利自动终止。也就是说，你无法获得图灵班网站的 CC BY-NC-SA 4.0 提供的共享和演绎方面的权利。

综上，该首页声明违反了上游图灵班网站的 CC BY-NC-SA 4.0 许可协议，无法获得共享和演绎权利，现在处于侵权状态，请贵团队根据第六条 b 款要求在 30 日内进行修改，以恢复权利。

**Comment by for-mydream** [comment]
抱歉，这是我的疏忽。我为对于许可内容的不了解造成的侵权而致歉。我将会立即修改这个不合理表述。对于对贵网站造成的麻烦深表歉意
